[package]
name = "translator-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
translator-core = { path = "../translator-core", features = ["clap"] }
clap = { version = "4", features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0"
